[tool.poetry]
name = "redispraktika"
version = "0.1.0"
description = ""
authors = ["nbax <nils@nbax.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
redis = "^5.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
